apiVersion: v1
kind: Service
metadata:
  name: iti-kotlin-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.labels.app }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
