apiVersion: v2
name: iti-kotlin
description: A production-ready Helm chart for a Kotlin Ktor API
type: application

version: 0.1.1
appVersion: "1.0.0"

keywords:
  - kotlin
  - ktor
  - api
  - backend

maintainers:
  - name: roberto
